import java.util.Random;
import java.util.Scanner;

/**
 * A simple random number guessing game.
 * The user tries to guess the number generated by the system (1 to 10).
 */
public class RandomGame {

    public static void main(String[] args) {

        final var randomNumber = new Random();
        final var scanner = new Scanner(System.in);


        while (true) {
            System.out.println("Guess what the system might output");
            System.out.println("========================");
            System.out.println("\n");
            System.out.print("Enter a number between 1 and 10: ");

            int enteredInput;
            try {
                enteredInput = scanner.nextInt();
                scanner.nextLine();
            } catch (Exception e) {
                System.out.print("insert a number bro WTF ---- ");
                scanner.nextLine();
                continue;
            }

            if (enteredInput < 1 || enteredInput > 10) {
                System.out.println("did you not see i said from 1 to 10 you avo");
                continue;
            }

            System.out.println("The number you picked is: " + enteredInput);

            final var systemNumber = randomNumber.nextInt(10) + 1;

            if (enteredInput == systemNumber) {
                System.out.println("Congratulations! You guessed it right.");
                break;
            }

            System.out.println("The System picked: " + systemNumber + " you have failed");

            String userYesNo;

            while (true) {
                System.out.println("Try again?");
                System.out.println("Yes to retry and No to exit the game");
                userYesNo = scanner.nextLine();

                if (userYesNo.equalsIgnoreCase("No")) {
                    System.out.println("I see you done you little mango");
                    scanner.close();
                    return;
                } else if (userYesNo.equalsIgnoreCase("Yes")) {
                    break;
                } else {
                    System.out.println("\n");
                    System.out.println("what the f*ck did you just enter? try that again");
                }
            }
        }
        scanner.close();
    }
}

